### ISSUE TITLE
Numerous Windows vscode observations

### ISSUE THREAD

**Issue by philipsoeberg** [DionJChapman/Localization-Internationalization-Editor#20]
Hi,
I saw from your commit history that you've been attempting to fix various Windows path issues, so maybe they are related.
I installed v3.1.3 from vscode-marketplace on a vscode 1.81.1 running under Windows 11.
I have a flutter project with lib/l10n/[app_en.arb intl_da.arb] files.

1) Right-clicking the l10n folder reveals two "Open In i18n/l10n Editor" options. Both seem to do same.

2) In editor, clicking [Add] inserts a new blank "Key.." field under KEY column, but no fields are added to app_en or intl_da columns. HItting save clears the key as no value has been entered. I simply cannot add keys this way.

3) Switching to "detail-view" (in lack of a better word for the upper-rightmost-button), I get a blue-box with my keys but nothing else on this dialog. Having tried innwin release I know it should display value boxes for the two languages. It does nothing

4) Marking text in dart-code -> ctrl+. -> Add text to i18n/l10n editor yields a prompt for a key-name. Hit enter. new prompt for description. hit enter. Result is error with "Webview is disposed". 

(4) stack-trace is
`2023-08-10 19:32:24.552 [error] Error: Webview is disposed
	at R.c (c:\Users\ps\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:36981)
	at get webview [as webview] (c:\Users\ps\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:36134)
	at IJEManager.search (c:\Users\ps\.vscode\extensions\nativebit.i18n-l10n-editor-3.1.3\out\i18n-l10n-editor\ije-manager.js:99:21)
	at applySaveAndRunFlutterPubGet (c:\Users\ps\.vscode\extensions\nativebit.i18n-l10n-editor-3.1.3\out\i18n-l10n-editor\applySaveAndRunFlutterPubGet.js:50:42)
	at c:\Users\ps\.vscode\extensions\nativebit.i18n-l10n-editor-3.1.3\out\extension.js:28:200
	at a.h (c:\Users\ps\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:77777)
	at a.g (c:\Users\ps\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:76772)
	at a.executeCommand (c:\Users\ps\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:76679)
	at Object.executeCommand (c:\Users\ps\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:120:20977)
	at c:\Users\ps\.vscode\extensions\nativebit.i18n-l10n-editor-3.1.3\out\extension.js:26:35
	at async a.h (c:\Users\ps\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:77769)
	at async a.h (c:\Users\ps\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:77769) i18n-l10n-editor.inputBox undefined`

**Comment by DionJChapman** [comment]
Hi

Could you please send me your l10n.yaml and the l10n directory so I can test with what you have?

**Comment by DionJChapman** [comment]
> * In editor, clicking [Add] inserts a new blank "Key.." field under KEY column, but no fields are added to app_en or intl_da columns. HItting save clears the key as no value has been entered. I simply cannot add keys this way.
>

I can not reproduce it so that it only has the Key field. I have found that if you only add the key and no text in the base translation then it will not save. I will change this so it will automatically add the key to the base translation so it can be saved.

> * Switching to "detail-view" (in lack of a better word for the upper-rightmost-button), I get a blue-box with my keys but nothing else on this dialog. Having tried innwin release I know it should display value boxes for the two languages. It does nothing

I have found that it will not show the fields until you select a key. Also, it overlaps in Windows. I will change this so the first key is selected when you change to the Tree view, as it is called.

**Comment by DionJChapman** [comment]
> 4\. Marking text in dart-code -> ctrl+. -> Add text to i18n/l10n editor yields a prompt for a key-name. Hit enter. new prompt for description. hit enter. Result is error with "Webview is disposed".

Added code to detect when the editor has been closed and then reopen the editor. Release in v3.1.4

**Comment by DionJChapman** [comment]
> 1. Right-clicking the l10n folder reveals two "Open In i18n/l10n Editor" options. Both seem to do same.

Fixed the issue where the Context Menu item would sometimes appear twice.

**Comment by philipsoeberg** [comment]
> Hi
> 
> Could you please send me your l10n.yaml and the l10n directory so I can test with what you have?

Sure, attached is a zip. It also includes two screenshots of the editor+detail view with the reported observations.
If I go back and use https://marketplace.visualstudio.com/items?itemName=innwin.i18n-arb-editor the editor does display correctly in both views.

[l10n.1.zip](https://github.com/DionJChapman/Localization-Internationalization-Editor/files/12319804/l10n.1.zip)

**Comment by DionJChapman** [comment]
> Sure, attached is a zip. It also includes two screenshots of the editor+detail view with the reported observations.
> If I go back and use https://marketplace.visualstudio.com/items?itemName=innwin.i18n-arb-editor the editor does display correctly in both views.

Hi, Thanks for that. The version you are refering to is much older and has a bug in it where you can end up with files being just {}. Make sure you have a back up when using it.

My l10n.yaml file is as follows. the first 2 lines are required by the documentaion. I have added code to use default values and update the file if not found.
`arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: missing.log
nullable-getter: false
`

In my Dropbox is a zipped .vsix file, unzip this to the root of your project and right click it. Then down near the bottom of the context menu choose **Install Extension VSIX** and then reload. You should then be able to text the fixes I have done.

Dropbox: https://www.dropbox.com/s/zp1jvpye9wu5bn0/i18n-l10n-editor-3.1.4.vsix.zip?dl=0

**Comment by philipsoeberg** [comment]
> Hi, Thanks for that. The version you are refering to is much older and has a bug in it where you can end up with files being just {}. Make sure you have a back up when using it.

Yeah, I just use it read-only to compare. I am still so-so on the whole ARB idea compared to Darts intl.messages(), but try to follow flutters guidelines even though JSON format is terrible for humans and language sync is apparently not part of flutters thought process. But this leaves room for your excellent plugin :) @key and key sort and key-sync between languages is super important.

> 
> My l10n.yaml file is as follows. the first 2 lines are required by the documentaion. I have added code to use default values and update the file if not found. `arb-dir: lib/l10n/arb
> 
> template-arb-file: app_en.arb
> 
> output-localization-file: app_localizations.dart
> 
> untranslated-messages-file: missing.log nullable-getter: false `
If you are refering to flutter official [documenation](https://docs.flutter.dev/ui/accessibility-and-localization/internationalization#configuring-the-l10nyaml-file), I read it as the two directives being optional with default values provided by `gen-l10n` tool. I do see example snippets often having the two lines in the l10n, but I didn't read it as mandatory. 

> 
> In my Dropbox is a zipped .vsix file, unzip this to the root of your project and right click it. Then down near the bottom of the context menu choose **Install Extension VSIX** and then reload. You should then be able to text the fixes I have done.
> 
> Dropbox: https://www.dropbox.com/s/zp1jvpye9wu5bn0/i18n-l10n-editor-3.1.4.vsix.zip?dl=0

Excellent, I'll give it a go.

**Comment by DionJChapman** [comment]
> If you are refering to flutter official [documenation](https://docs.flutter.dev/ui/accessibility-and-localization/internationalization#configuring-the-l10nyaml-file), I read it as the two directives being optional with default values provided by `gen-l10n` tool. I do see example snippets often having the two lines in the l10n, but I didn't read it as mandatory.
> 
> >

If you look at point number 3 under https://docs.flutter.dev/ui/accessibility-and-localization/internationalization#adding-your-own-localized-messages it says to add them. I took that as needed to be there.

Setting **i18n-l10n-editor.sortKeyTogether** to true will keep the key and @keys together and make the file much more readable.

**Comment by philipsoeberg** [comment]
> If you look at point number 3 under https://docs.flutter.dev/ui/accessibility-and-localization/internationalization#adding-your-own-localized-messages it says to add them. I took that as needed to be there.

Sure, but it also says `[..] In this example, you’ve done the following`. Anyway, I would personally prefer extensions adopting default values without relying on config files, but it works and does no damage so I'm fine :)

> 
> Setting **i18n-l10n-editor.sortKeyTogether** to true will keep the key and @keys together and make the file much more readable.

Yes, Its already enabled. imho I would default it to on as it really makes it difficult to use the ARB file after a sort without @key and key being paired. Excellent feature.

So far v3.1.4 has editor working.

I also tried the `Extract-to-i18n/l10n editor`:
1) As it opens the editor, it displays a new "Folder" column and have only the new keys listed. Pressing save and reloading editor then has all the old keys + the new key, so it works. I just find the differing dialog view a little confusing.
2) It would be nice if the extracted text was replaced with the variable name in the source .dart file, also with whatever context-construct the user has chosen. I use context.l10n.<key-name> others use loc.<key-name> and documentation goes via AppLocations.of(context)!.<key-name>.
3) The right-hand-arrow-button, which I presume should copy app_en text to intl_da as-is does not do anything IF the field is empty. It does overwrite the field if anything other than null is present. The Microsoft translator button works fine 👍 

Also tried the Microsoft translator.. works fine 👍

**Comment by DionJChapman** [comment]
> Yes, Its already enabled. imho I would default it to on as it really makes it difficult to use the ARB file after a sort without @key and key being paired. Excellent feature.

Done.



> 2\. It would be nice if the extracted text was replaced with the variable name in the source .dart file, also with whatever context-construct the user has chosen. I use `context.l10n.<key-name>` others use `loc.<key-name>` and documentation goes via `AppLocations.of(context)!.<key-name>`.

It is planed, it will be a setting where you put what you want placed in front of <key name>

The other 2 I will look into.

Thanks for you testing.

**Comment by DionJChapman** [comment]
> > Yes, Its already enabled. imho I would default it to on as it really makes it difficult to use the ARB file after a sort without @key and key being paired. Excellent feature.
> 
> Done.
> 
> > 2. It would be nice if the extracted text was replaced with the variable name in the source .dart file, also with whatever context-construct the user has chosen. I use `context.l10n.<key-name>` others use `loc.<key-name>` and documentation goes via `AppLocations.of(context)!.<key-name>`.
> 
> It is planed, it will be a setting where you put what you want placed in front of
> 
> The other 2 I will look into.
> 
> Thanks for you testing.

PS. i have an issue that when using sub languages such as zh-Hans that _flutter gen-l10n_ requires you to have files for both zh-Hans and zh so need to automate that as well.

**Comment by DionJChapman** [comment]
> 1. As it opens the editor, it displays a new "Folder" column and have only the new keys listed. Pressing save and reloading editor then has all the old keys + the new key, so it works. I just find the differing dialog view a little confusing.

I assume you're opening the editor by highlighting some text and adding it that way. When it does this it searches for the keys so it is easy to edit (not mixed in with every other key). You can clear the search text to see all the keys. I have added text beside the search field to make it clearer.



> 3\. The right-hand-arrow-button, which I presume should copy app_en text to intl_da as-is does not do anything IF the destination field is empty. It does overwrite the field if anything other than null is present. The Microsoft translator button works fine

I have fixed this now, it will copy to blank translations.

New test file: https://www.dropbox.com/s/zp1jvpye9wu5bn0/i18n-l10n-editor-3.1.4.vsix.zip?dl=0

**Comment by philipsoeberg** [comment]
> I have fixed this now, it will copy to blank translations.

Checked, working 👍 

When I add a string to the editor (editor is closed, select text, ctrl+., extract to ...), this is the dialog i get:
![image](https://github.com/DionJChapman/Localization-Internationalization-Editor/assets/20000539/51f8cc37-1f12-46d3-81c1-11be7bca1c24)

It has a "Folder" column and a new blue button next to the key. If i press that button i get a popup "Translation files saved", then a duplication view of keys and if I fiddle with the Folder drop-down I'm locked into a "They key path is already defined" fault.
![image](https://github.com/DionJChapman/Localization-Internationalization-Editor/assets/20000539/bdd8aabb-fe1e-472b-8f15-75c169a7580d)

**Comment by DionJChapman** [comment]
> > I have fixed this now, it will copy to blank translations.
> 
> Checked, working 👍
> 
> When I add a string to the editor (editor is closed, select text, ctrl+., extract to ...), this is the dialog i get: ![image](https://user-images.githubusercontent.com/20000539/259992441-51f8cc37-1f12-46d3-81c1-11be7bca1c24.png)
> 
> It has a "Folder" column and a new blue button next to the key. If i press that button i get a popup "Translation files saved", then a duplication view of keys and if I fiddle with the Folder drop-down I'm locked into a "They key path is already defined" fault. ![image](https://user-images.githubusercontent.com/20000539/259992824-bdd8aabb-fe1e-472b-8f15-75c169a7580d.png)

It looks as if you have 2 builds in your project with 2 language folders. The folder there is to show which folder the language is in and to change a translation between folders. 

In the second picture, because you change the folder and the key is already in that folder, it is giving you an error. I have no idea why they allow the changing of the folders in the previous versions.

I have tried not to remove features from the previous versions. But in this case, it is confusing, and I am thinking of removing this and just having the folder name as non-selectable.

What is your opinion of this?

**Comment by philipsoeberg** [comment]
> It looks as if you have 2 builds in your project with 2 language folders. The folder there is to show which folder the language is in and to change a translation between folders.
> 
> In the second picture, because you change the folder and the key is already in that folder, it is giving you an error. I have no idea why they allow the changing of the folders in the previous versions.

I only have 1 flutter project on my machine. It resides in c;\dev\tms\client and follows flutters structure from that root path.
It must be a bug for the editor to display client/lib/l10n and lib/l10n as two separate projects.
 
> I have tried not to remove features from the previous versions. But in this case, it is confusing, and I am thinking of removing this and just having the folder name as non-selectable.
> 
> What is your opinion of this?

I would scrap code which makes no sense to you, or tag it with "Experimental" and turn it off until someone else badly needs it so that use-case can be discussed and understood.

**Comment by DionJChapman** [comment]
> I only have 1 flutter project on my machine. It resides in c;\dev\tms\client and follows flutters structure from that root path. It must be a bug for the editor to display client/lib/l10n and lib/l10n as two separate projects.
> 
> >

It is picking up client/lib/l10n as one folder and lib/l10n as the second folder. It is working correctly then.



> I would scrap code which makes no sense to you, or tag it with "Experimental" and turn it off until someone else badly needs it so that use-case can be discussed and understood.

I have changed it and released it with the change. I tag releases so I can easily get that back if needed.

Thanks for the help in fixing these issues.
