### ISSUE TITLE
ICU arguments has char removed when using translation service

### ISSUE THREAD

**Issue by philipsoeberg** [DionJChapman/Localization-Internationalization-Editor#27]
When I hit "Translate-via-microsoft-translation-service" for a key with value which contain {}, the source-value is modified so that the character before all { is erased. This new modified value is then translated and inserted to target language.

Needless to say, modifying source-value when hitting translate is not working correctly.

Before translate-button-was-hit:
"testKey":"testValue with {argument}"

After translate-button-was-hit:
"testKey":"testValue with{arguemnt}"

in the source file! It obviously also affects destination file.

**Comment by DionJChapman** [comment]
> When I hit "Translate-via-microsoft-translation-service" for a key with value which contain {}, the source-value is modified so that the character before all { is erased. This new modified value is then translated and inserted to target language.

Thanks for that. I will look tomorrow, should be an easy fix.

**Comment by DionJChapman** [comment]
> When I hit "Translate-via-microsoft-translation-service" for a key with value which contain {}, the source-value is modified so that the character before all { is erased. This new modified value is then translated and inserted to target language.

I have had to go back to the drawing board on the Amazon Translation service I was working on, so I have fixed this.

This is now available to install v3.2.3
