### ISSUE TITLE
Key Case Style forcing camelCase on save

### ISSUE THREAD

**Issue by TheFabbiusCorp** [DionJChapman/Localization-Internationalization-Editor#34]
**Describe the bug**
The property defaults to camelCase and any other choice falls back to that.

**To Reproduce**
Try to save a key separated by underscores and it will be saved as camelCase.

**Expected behavior**
If 'no change' is set, the key must be saved as such.

**Screenshots**
<img width="612" alt="image" src="https://github.com/DionJChapman/Localization-Internationalization-Editor/assets/8267992/4075651c-1b2f-4fff-aa87-bcab4a500ede">

**Comment by DionJChapman** [comment]
> **Describe the bug**
> The property defaults to camelCase and any other choice falls back to that.

I can not really reproduce this camelCase, but I have found it is removing anything other that a-z and 0-9 and have fixed that.

Also found a few other bugs that will be fixed in the next release.

**Comment by TheFabbiusCorp** [comment]
Yes, it works now! :) Thank you!!
